version: '3.8'

networks:
  projet-baknine-network:
    driver: overlay   

services:
  frontend:
    image: localhost:7000/frontend-image-final:1.0.0
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - projet-baknine-network
    deploy:
      replicas: 2  
      restart_policy:
        condition: on-failure  

  backend:
    image: localhost:7000/backend-image-final:1.0.0
    container_name: backend-container
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.0.1.3:5432/projet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nouhaila
    depends_on:
      - database
    networks:
      - projet-baknine-network
    deploy:
      replicas: 1  
      restart_policy:
        condition: on-failure

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nouhaila
      POSTGRES_DB: projet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d projet"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - projet-baknine-network
    deploy:
      replicas: 1 
      placement:
        constraints:
          - node.role == manager  
volumes:
  postgres-data:
  
